# Generated by Django 3.1.1 on 2020-09-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='stripeCustomerId',
            field=models.CharField(max_length=255),
        ),
    ]
